### ISSUE TITLE
Advanced Line Req - One or More lines have errors 

### ISSUE THREAD

**Issue by MZAMAN0** [document-capture/Advanced-Line-Recognition#2]
I am using advance line req code unit, which pick up all the lines but then the comments say "one or more lines have errors"
without any real explanation of what the error is. The lines have been correctly configured and can not understand what is the issue.

**Comment by sradloff** [comment]
Hi @MZAMAN0, this shouldn't be related with the adv. line recognition as it is raised by default document or line validation.
Best guess it, that you e.g. miss a quantity, price, item translation. 
If you are a partner and cannot solve it yourself please submit a ticket in the Continia PartnerZone. 
As end user you should contact your partner to assist you. A screenshot (anonymized) of the document situation could also help.

**Comment by MZAMAN0** [comment]
Hi Sebastian,

Thank you for taking your response.

I am working for a Continia partner and the lines have been configured
correctly with correct translate and all required fields. The error onlys
shows when ALR is used.

I have tried contacting Continia but there is limited support on ALR.

Kind Regards
Mo

**Comment by sradloff** [comment]
Can you send me the ticket no.?

**Comment by MZAMAN0** [comment]
I do not have a ticket number directly related to this as I did with a
member Continia support team over a teams call.

Kind regards
Mo

**Comment by sradloff** [comment]
Hi,
I'll close this issue as it seems not to be related with the advanced line recognition. Feel free to contact me directly or via Continia Partner support if you need any further help to solve your requirements.
Kind regards
Sebastian
