### ISSUE TITLE
Fehlermeldung Modul Bestellabgleich

### ISSUE THREAD

**Issue by elemmerz** [document-capture/Advanced-Line-Recognition#4]
Hallo zusammen,
die aktuelle Version kann scheinbar nur noch verwendet werden, wenn das Modul Bestellabgleich aktiv ist. Die Funktion "Felder erkennen" lässt sich dadurch nicht mehr ohne Fehler mit Hinweis darauf durchführen. In den Vorlagen wurde das Feld "Auto. Suche nach Bestellnummer" eingefügt, das stammt aus einer anderen Erweiterung, wenn ich das richtig gesehen habe. 

Viele Grüße

**Comment by sradloff** [comment]
Hallo,
ich werde das prüfen und ggf. mit einem Update korrigieren.

**Comment by sradloff** [comment]
I solved the issue by switching the param to false in function call CDCModuleLicense.IsMatchingActivated() inside function FindAllPONumbersInDocument in codeunit 61001.
